[package]
name = "kcp-rs-z"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
thiserror = "1.0"


[build-dependencies]
bindgen = "0.64"
cc = "1.0"